### ISSUE TITLE
Warning: Please set TIN no in company

### ISSUE THREAD

**Issue by Chandresh-SerpentCS** [indictranstech/fedex_integration#2]
I am using your FedEx-integration module in my erpnext site.

In that, I get a warning at a time of creating the Packing Slip.

In my shipping address, there is no any field in Address to relate my shipping address to the company.

I have already set tin no. in my base company, but how to relate this company to my shipping address.

So currently I get None value in the company.

Can you help me to solve this problem?

![image](https://cloud.githubusercontent.com/assets/17649094/26618186/0e316a3a-45f7-11e7-9d2c-ea734aa2a070.png)

**Comment by suyashphadtare** [comment]
If you are on version 8 then this app is yet not compatible with it.
Linking of Customer, Company etc are moved into child table in Address doctype in V8.
I have to make necessary changes to make it compatible.

As of now, You can use it with version 7.
For version 7, you can link company by checking **Is your company Address** & specifying **Company**

**Comment by Chandresh-SerpentCS** [comment]
@suyashphadtare 
Hello,
In v8, there is also field like **is your company address** and I also add the company name into that.

**Comment by suyashphadtare** [comment]
@Chandresh-SerpentCS 

Yes In V8 there is field **Is Your Company Address** but company name can be specified in child table. But my current code is not fetching it from child table so it is getting None value.

I will update for version 8 later. Meanwhile, you can try with V7.

**Comment by Chandresh-SerpentCS** [comment]
@suyashphadtare 
Ok, thank you for your valuable reply.
